#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v16
# autospec commit: b858a2a
#
Name     : R-mstate
Version  : 0.3.3
Release  : 45
URL      : https://cran.r-project.org/src/contrib/mstate_0.3.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/mstate_0.3.3.tar.gz
Summary  : Data Preparation, Estimation and Prediction in Multi-State
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-mstate-lib = %{version}-%{release}
Requires: R-RColorBrewer
Requires: R-data.table
Requires: R-rlang
Requires: R-viridisLite
BuildRequires : R-RColorBrewer
BuildRequires : R-data.table
BuildRequires : R-rlang
BuildRequires : R-viridisLite
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# mstate
<!-- badges: start -->
[![](https://www.r-pkg.org/badges/version/mstate?color=orange)](https://cran.r-project.org/package=mstate)
[![](http://cranlogs.r-pkg.org/badges/last-month/mstate?color=gray)](https://cran.r-project.org/package=mstate)
[![](http://cranlogs.r-pkg.org/badges/grand-total/mstate?color=blue)](https://cran.r-project.org/package=mstate)
[![](https://img.shields.io/badge/doi-10.1002/sim.2712-yellow.svg)](https://doi.org/10.1002/sim.2712)
<!-- badges: end -->

%package lib
Summary: lib components for the R-mstate package.
Group: Libraries

%description lib
lib components for the R-mstate package.


%prep
%setup -q -n mstate
pushd ..
cp -a mstate buildavx2
popd
pushd ..
cp -a mstate buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720801781

%install
export SOURCE_DATE_EPOCH=1720801781
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/mstate/CITATION
/usr/lib64/R/library/mstate/DESCRIPTION
/usr/lib64/R/library/mstate/INDEX
/usr/lib64/R/library/mstate/Meta/Rd.rds
/usr/lib64/R/library/mstate/Meta/data.rds
/usr/lib64/R/library/mstate/Meta/features.rds
/usr/lib64/R/library/mstate/Meta/hsearch.rds
/usr/lib64/R/library/mstate/Meta/links.rds
/usr/lib64/R/library/mstate/Meta/nsInfo.rds
/usr/lib64/R/library/mstate/Meta/package.rds
/usr/lib64/R/library/mstate/Meta/vignette.rds
/usr/lib64/R/library/mstate/NAMESPACE
/usr/lib64/R/library/mstate/NEWS.md
/usr/lib64/R/library/mstate/R/mstate
/usr/lib64/R/library/mstate/R/mstate.rdb
/usr/lib64/R/library/mstate/R/mstate.rdx
/usr/lib64/R/library/mstate/data/aidssi.RData
/usr/lib64/R/library/mstate/data/aidssi2.RData
/usr/lib64/R/library/mstate/data/bmt.RData
/usr/lib64/R/library/mstate/data/ebmt1.RData
/usr/lib64/R/library/mstate/data/ebmt2.RData
/usr/lib64/R/library/mstate/data/ebmt3.RData
/usr/lib64/R/library/mstate/data/ebmt4.RData
/usr/lib64/R/library/mstate/data/prothr.RData
/usr/lib64/R/library/mstate/doc/Tutorial.R
/usr/lib64/R/library/mstate/doc/Tutorial.Rnw
/usr/lib64/R/library/mstate/doc/Tutorial.pdf
/usr/lib64/R/library/mstate/doc/index.html
/usr/lib64/R/library/mstate/doc/visuals_demo.R
/usr/lib64/R/library/mstate/doc/visuals_demo.Rmd
/usr/lib64/R/library/mstate/doc/visuals_demo.html
/usr/lib64/R/library/mstate/help/AnIndex
/usr/lib64/R/library/mstate/help/aliases.rds
/usr/lib64/R/library/mstate/help/mstate.rdb
/usr/lib64/R/library/mstate/help/mstate.rdx
/usr/lib64/R/library/mstate/help/paths.rds
/usr/lib64/R/library/mstate/html/00Index.html
/usr/lib64/R/library/mstate/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/mstate/libs/mstate.so
/V4/usr/lib64/R/library/mstate/libs/mstate.so
/usr/lib64/R/library/mstate/libs/mstate.so
